backend: piper
rate: 180
volume: 0.7
voice_ro_hint: "ro"
voice_en_hint: "en"

piper:
  exe: "/home/dani/conversational_bot/Conversational_Bot/.venv/bin/piper"     # verificÄƒ cu: which piper
  model_ro: "voices/ro_RO-mihai-medium.onnx"
  config_ro: "voices/ro_RO-mihai-medium.onnx.json"
  model_en: "voices/en_US-amy-medium.onnx"
  config_en: "voices/en_US-amy-medium.onnx.json"
  speaker_id: null
  length_scale: 1.0
  noise_scale: 0.667
  noise_w: 0.8
  sentence_silence_ms: 80
